# Build stage
FROM --platform=$BUILDPLATFORM node:20-alpine AS build

WORKDIR /app

RUN npm install -g pnpm@latest

COPY frontend/package*.json frontend/pnpm-lock.yaml ./
RUN pnpm install
COPY frontend/ ./
RUN pnpm build

# Production Nginx stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
