services:
  backend:
    image: ghcr.io/rzv1/iss-harvest-backend:latest
    container_name: harvest-backend
    restart: unless-stopped
    environment:
      - PORT=3000
      - DATABASE_URL=file:./dev.db
      - PRISMA_USER_CONSENT_FOR_DANGEROUS_AI_ACTION=yes
    volumes:
      - ./backend/prisma/dev.db:/app/prisma/dev.db
    networks:
      - internal-net

  frontend:
    image: ghcr.io/rzv1/iss-harvest-frontend:latest
    container_name: harvest-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - proxy-network
      - internal-net
networks:
  proxy-network:
    external: true
  internal-net:
    driver: bridge
