FROM node:20-alpine
WORKDIR /app

RUN apk add --no-cache python3 make g++
RUN npm install -g pnpm@latest

COPY backend/package*.json backend/pnpm-*.yaml ./
COPY backend/prisma ./prisma

RUN pnpm install
RUN pnpm exec prisma generate

COPY backend/ ./

EXPOSE 3000
CMD ["npm", "start"]
