server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Serve static frontend files with SPA fallback
    location / {
	proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Proxy relative /api/ requests to the backend service
    location /api/ {
        proxy_pass http://backend:3000/; # back-end-ul ruleaza intr-o retea interna (docker)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr; # trimite la backend ip-ul real al utilizatorului
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # adauga ip-ul clientului intr-o lista de proxy-uri parcurse
        proxy_set_header X-Forwarded-Proto $scheme; # trimite protocolul
    }
}
